title: BIOS2 training materials
email: https://www.dataone.org/contact
description: > # this means to ignore newlines until "baseurl:"
  The BIOS2 online resources contain lessons, slides and reference material describing computation tools for biodiversity science. These resources are intended for researchers and students, and are created by scientists associated with BIOS2.
baseurl: "/education" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _bios2
github_username:  bios2
analytics_code: ""
show_content_type_filter: 1   #Set this to 1 to show the "Filter by content type" option on the home page.
show_debug: 0
life_cycle_steps: ["plan","collect","assure","describe","preserve","discover","integrate","analyze"]

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "_bestpractices/README.md"
  - "_bestpractices/_config.yml"
  - "_bestpractices/index.md"
  - "_lessons/_includes"
  - "_lessons/_layouts"
  - "_lessons/_lessons"
  - "_lessons/css"
  - "_lessons/img"
  - "_lessons/js"
  - "_lessons/MegansEditing"
  - "_lessons/resources"
  - "_lessons/templates"
  - "_lessons/_config.yml"
  - "_lessons/Gemfile"
  - "_lessons/LICENSE"
  - "_lessons/Makefile"
  - "_lessons/README.md"
  - "_lessons/remark2pdf"

# Format for the slides, can be either 16:9 or 4:3
format: '16:9'

# Collections
collections:
  lessons:
    output: true
    output_ext: .html
    permalink: :path
  bestpractices:
    output: true
    output_ext: .html
    permalink: :path
  videos:
    output: true
    output_ext: .html
    permalink: :path

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "slides"
